name: merge-requst

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - uses: pdm-project/setup-pdm@v4
            # You are now able to use PDM in your workflow
      - run: pdm install
      - run: pdm run test