name: merge-requst

on: [pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
            # You are now able to use PDM in your workflow
      - name: Install dependencies
        run: pdm install
      - name: Test with pytest
        run: |
          pdm run test